

services:
  postgres:
    image: postgres:15     # Указываем версию PostgreSQL
    container_name: hh_postgres
    restart: always
    environment:
      POSTGRES_USER: admin     # Имя пользователя
      POSTGRES_PASSWORD: password # Пароль пользователя
      POSTGRES_DB: hh_db         # Название базы данных
    ports:
      - "5432:5432"              # Открываем порт для подключения
    volumes:
      - postgres_data:/var/lib/postgresql/data # Хранение данных на хосте

volumes:
  postgres_data:
