// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: proto/resume.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // Уникальный идентификатор
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // Имя пользователя
	Position    string   `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`                          // Желаемая позиция
	Skills      string   `protobuf:"bytes,4,opt,name=skills,proto3" json:"skills,omitempty"`                              // Навыки
	Experience  string   `protobuf:"bytes,5,opt,name=experience,proto3" json:"experience,omitempty"`                      // Опыт работы
	ContactInfo string   `protobuf:"bytes,6,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"` // Контактная информация
	Tags        []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                                  // Теги для фильтрации
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_proto_resume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{0}
}

func (x *Resume) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Resume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resume) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Resume) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *Resume) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *Resume) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *Resume) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ResumeID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ResumeID) Reset() {
	*x = ResumeID{}
	mi := &file_proto_resume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeID) ProtoMessage() {}

func (x *ResumeID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeID.ProtoReflect.Descriptor instead.
func (*ResumeID) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResumesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"` // Фильтр для резюме
}

func (x *GetResumesRequest) Reset() {
	*x = GetResumesRequest{}
	mi := &file_proto_resume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumesRequest) ProtoMessage() {}

func (x *GetResumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumesRequest.ProtoReflect.Descriptor instead.
func (*GetResumesRequest) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{2}
}

func (x *GetResumesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type Resumes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resumes []*Resume `protobuf:"bytes,1,rep,name=resumes,proto3" json:"resumes,omitempty"`
}

func (x *Resumes) Reset() {
	*x = Resumes{}
	mi := &file_proto_resume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resumes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resumes) ProtoMessage() {}

func (x *Resumes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resumes.ProtoReflect.Descriptor instead.
func (*Resumes) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{3}
}

func (x *Resumes) GetResumes() []*Resume {
	if x != nil {
		return x.Resumes
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_resume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{4}
}

var File_proto_resume_proto protoreflect.FileDescriptor

var file_proto_resume_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0xb7, 0x01, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x33, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xdb, 0x01,
	0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x30, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12,
	0x0e, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x1a,
	0x10, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49,
	0x44, 0x12, 0x38, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x12,
	0x19, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x0e, 0x2e, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x1a, 0x0d, 0x2e, 0x72, 0x65,
	0x73, 0x75, 0x6d, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2f, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x10, 0x2e, 0x72, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x44, 0x1a, 0x0d, 0x2e, 0x72,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x11, 0x5a, 0x0f, 0x68,
	0x68, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_resume_proto_rawDescOnce sync.Once
	file_proto_resume_proto_rawDescData = file_proto_resume_proto_rawDesc
)

func file_proto_resume_proto_rawDescGZIP() []byte {
	file_proto_resume_proto_rawDescOnce.Do(func() {
		file_proto_resume_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_resume_proto_rawDescData)
	})
	return file_proto_resume_proto_rawDescData
}

var file_proto_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_resume_proto_goTypes = []any{
	(*Resume)(nil),            // 0: resume.Resume
	(*ResumeID)(nil),          // 1: resume.ResumeID
	(*GetResumesRequest)(nil), // 2: resume.GetResumesRequest
	(*Resumes)(nil),           // 3: resume.Resumes
	(*Empty)(nil),             // 4: resume.Empty
}
var file_proto_resume_proto_depIdxs = []int32{
	0, // 0: resume.Resumes.resumes:type_name -> resume.Resume
	0, // 1: resume.ResumeService.CreateResume:input_type -> resume.Resume
	2, // 2: resume.ResumeService.GetResumes:input_type -> resume.GetResumesRequest
	0, // 3: resume.ResumeService.UpdateResume:input_type -> resume.Resume
	1, // 4: resume.ResumeService.DeleteResume:input_type -> resume.ResumeID
	1, // 5: resume.ResumeService.CreateResume:output_type -> resume.ResumeID
	3, // 6: resume.ResumeService.GetResumes:output_type -> resume.Resumes
	4, // 7: resume.ResumeService.UpdateResume:output_type -> resume.Empty
	4, // 8: resume.ResumeService.DeleteResume:output_type -> resume.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_resume_proto_init() }
func file_proto_resume_proto_init() {
	if File_proto_resume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_resume_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_resume_proto_goTypes,
		DependencyIndexes: file_proto_resume_proto_depIdxs,
		MessageInfos:      file_proto_resume_proto_msgTypes,
	}.Build()
	File_proto_resume_proto = out.File
	file_proto_resume_proto_rawDesc = nil
	file_proto_resume_proto_goTypes = nil
	file_proto_resume_proto_depIdxs = nil
}
